"""
This is a module with the keys used in the extracted dataframe that can be used for easy filtering and more.
"""


CORPORATION = "Bolag"
DATE = "Datum"
MARKET = "Lista"
ADVISOR = "Rådgivare"
VALUE_AT_IPO = "Börsvärde vid IPO"
N_FLAGS = "Flaggor"
CEO = "VD"
PRESIDENT = "Ordförande"
KEY_PERSON_STAKE = "Nyckelpersoners ägande (%)"
BIG_TIME_STAKEHOLDERS = "Storägare"
SELLING_STAKEHOLDERS = "Säljande aktieägare"
COMPANY_SIZE_CLASS = "Storleksklass"
STOCK_PRICE_OFFER = "Teckningskurs"
TOTAL_OFFER = "Erbjudande"
NEW_ISSUE_PART = "Andel nyemission (%)"
COMMITTED_IPO_ACTORS = "Teckningsåtagare"
GUARANTEED_ACTORS = "Garantiåtagare"
SECURED_STAKE = "Andel säkrad (%)"
AFFARSVARLDEN_ANALYSIS = "Affärsvärldens analys"
USED_OVERALLOCATION = "Utnyttjad övertilldelning (%)"
OUTCOME_TO_DATE = "Utveckling"
OUTCOME_FIRST_DAY = "Utveckling första handelsdag"
HOMEPAGE = "Hemsida"
ADDITIONAL_ADVISORS = "Övriga rådgivare"
